### ISSUE TITLE
$myhostname var hardcoded.  hostname failure with a suite not running on the localhost

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#36]
### How to Reproduce:
after install everything needed, packages etc. 

setup the env variable to external_server:
````
$TESTHOST=192.168.15.75
export TESTHOST
ping $TESTHOST
PING 192.168.15.75 (192.168.15.75) 56(84) bytes of data.
64 bytes from 192.168.15.75: icmp_seq=1 ttl=64 time=0.152 ms

```
````
rake 
```
### Error

```
unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)

es/smdba.feature
hostname: Name or service not known

@javascript @init_once
Feature: Create initial users
  In Order to run the tests
  As a testing users
  I need to create the admin and a testing users

  @first
  Scenario: Create Admin users and first org        # features/init_user_create.feature:11
    Given I access the host the first time          # features/step_definitions/access_steps.rb:13
      This scenario ran at: 2016-05-09 18:04:17 +0200
      unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)
      ./features/support/env.rb:113:in `block in <top (required)>'
      ./features/step_definitions/access_steps.rb:14:in `/^I access the host the first time$/'
      features/init_user_create.feature:12:in `Given I access the host the first time'

```

## Analyse: 

we have here the var $myhostname that is "hardcoded on the server", even if we set TESTHOST variable.

hostname -f
hostname: Name or service not known


```
features/support/env.rb:$myhostname = `hostname -f`
```

**Comment by MalloZup** [comment]
Do we need the variable hostname? i mean this could be done all with the ip-adress of server, even for web-testing.

I see then no much maintanance with that.

**Comment by MalloZup** [comment]
this is fixed on @slenkins branch
